In [61]:
from gcmc import GCMC
from packages import *

In [62]:
import time
import argparse
import cupy as cp 
import numpy as np

In [63]:
startTime = time.time()

In [64]:
startTime

1724992578.6118832

In [65]:
print('Start GCMC simulation at %s...' % time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()))


Start GCMC simulation at 2024-08-30 04:36:19...


In [66]:
parser = argparse.ArgumentParser(description="pyGCMC - A python package for GCMC simulation")


In [67]:
# args = parser.parse_args()
args, unknown = parser.parse_known_args() 

In [68]:
unknown

['--f=/home/jovyan/.local/share/jupyter/runtime/kernel-v2-3151007JnQ0q6wb6nXP.json']

In [69]:
"""
pygcmc -p 6v3g_silcs.1.pdb -t 6v3g_silcs.1.top -o output.txt -e 51 -n 1 
gcmc -v -p gcmc.75.inp > gcmc.75.out 
gcmc -p 6v3g_silcs.1.pdb -t 6v3g_silcs.1.top -o output.txt -e 54 -n 1
done
"""

'\npygcmc -p 6v3g_silcs.1.pdb -t 6v3g_silcs.1.top -o output.txt -e 51 -n 1 \ngcmc -v -p gcmc.75.inp > gcmc.75.out \ngcmc -p 6v3g_silcs.1.pdb -t 6v3g_silcs.1.top -o output.txt -e 54 -n 1\ndone\n'

In [70]:
import os, shutil

In [71]:
os.chdir('test/4wp7')

FileNotFoundError: [Errno 2] No such file or directory: 'test/4wp7'

In [72]:
os.listdir()

['4wp7_fixed_with_5l13_silcs.1.gc.75.pdb',
 '4wp7_fixed_with_5l13_silcs.1.prod.74.rec.pdb',
 '4wp7_fixed_with_5l13_silcs.1.gc.74.top',
 '4wp7_fixed_with_5l13_silcs.1.gc.75.top',
 'test.sh',
 '4wp7_fixed_with_5l13_silcs.1.prod.74.rec_out.pdb',
 'gcmc.75.inp',
 'gcmc.75.out',
 'charmm36.ff',
 'temp_link']

In [73]:
import os, shutil

In [74]:
# shutil.copytree("../../charmm36.ff", 'charmm36.ff')

In [75]:
# args.pdb_file="/home/jovyan/bo2/codes/mds/gcmc_py/test/4wp7/4wp7_fixed_with_5l13_silcs.1.gc.75.pdb"
# args.top_file="/home/jovyan/bo2/codes/mds/gcmc_py/test/4wp7/4wp7_fixed_with_5l13_silcs.1.gc.75.top"
args.out_file='gcmc_out.txt'
args.paramfile="/home/jovyan/bo2/codes/mds/gcmc_py/test/4wp7/gcmc.75.inp"

In [76]:
gcmc = GCMC()
# gcmc.load_parameters(args.paramfile)---> gcmc.config_dict
gcmc.load_parameters(args.paramfile)

/home/jovyan/bo2/codes/mds/gcmc_py/charmm36.ff !!!!
par ['charmm36.ff/ffnonbonded.itp', 'charmm36.ff/silcs.itp', 'charmm36.ff/nbfix.itp']
fragitp ['charmm36.ff/mol/benx.itp', 'charmm36.ff/mol/prpx.itp', 'charmm36.ff/mol/dmee.itp', 'charmm36.ff/mol/meoh.itp', 'charmm36.ff/mol/form.itp', 'charmm36.ff/mol/imia.itp', 'charmm36.ff/mol/acey.itp', 'charmm36.ff/mol/mamy.itp', 'charmm36.ff/mol/sol.itp']
atomtypes ['charmm36.ff/atomtypes.atp']
monomerdir ['charmm36.ff/mol']
top ['4wp7_fixed_with_5l13_silcs.1.gc.74.top']
pdb ['4wp7_fixed_with_5l13_silcs.1.prod.74.rec.pdb']
protitp ['4wp7_fixed_with_5l13_silcs.1.top']
grid_dx ['1.000']
box_size ['107.560  107.650   97.239']
gc_center ['67.780   67.825   62.620']
sys_center ['67.780   67.825   62.620']
energy_cutoff_frag ['8.000']
energy_cutoff_prot ['8.000']
use_group_cutoff ['yes']
use_cavity_bias ['yes']
use_conf_bias ['yes']
num_conf_bias_trial ['500']
use_const_water_nbar ['yes']
const_water_nbar ['56985']
random_seed ['166']
fragname ['benx  

In [77]:
pdb_file = gcmc.config_dict['pdb'][0]
top_file = gcmc.config_dict['top'][0]
top_out_file = gcmc.config_dict['op_top'][0]
pdb_out_file = gcmc.config_dict['op_pdb'][0]
print(f"Using pdb file: {pdb_file}")
print(f"Using top file: {top_file}")
print(f"Using output pdb file: {pdb_out_file}")
print(f"Using output top file: {top_out_file}")

Using pdb file: 4wp7_fixed_with_5l13_silcs.1.prod.74.rec.pdb
Using top file: 4wp7_fixed_with_5l13_silcs.1.gc.74.top
Using output pdb file: 4wp7_fixed_with_5l13_silcs.1.gc.75.pdb
Using output top file: 4wp7_fixed_with_5l13_silcs.1.gc.75.top


In [78]:
fragName = gcmc.config_dict['fragname'][0].split()
gcmc.fragmentName = [i.upper() for i in fragName]
fragmuex = gcmc.config_dict['fragmuex'][0].split()
gcmc.get_fragmuex(fragmuex)
fragconf = gcmc.config_dict['fragconf'][0].split()
gcmc.get_fragconf(fragconf)
fragconc = gcmc.config_dict['fragconc'][0].split()
gcmc.get_fragconc(fragconc)
mctime = gcmc.config_dict['mctime'][0].split()
gcmc.get_mctime(mctime)

In [82]:
gcmc.get_pdb(pdb_file)


Using pdb file: 4wp7_fixed_with_5l13_silcs.1.prod.74.rec.pdb
pdb atom number: 221441
pdb cryst: [132.126, 132.213, 122.07]
Total volume: 2132413.34447466


In [88]:
gcmc.get_top(top_file)


Using top file: 4wp7_fixed_with_5l13_silcs.1.gc.74.top
top atom number: 221441


In [91]:
# gcmc.get_psf(psf_file)
gcmc.get_simulation()

Read solute: BENX with 13 atoms
Read solute: PRPX with 12 atoms
Read solute: DMEE with 9 atoms
Read solute: MEOH with 6 atoms
Read solute: FORM with 6 atoms
Read solute: IMIA with 9 atoms
Read solute: ACEY with 8 atoms
Read solute: MAMY with 9 atoms
Read solute: SOL with 3 atoms
Using force field file: charmm36.ff/ffnonbonded.itp ,	nb number: 445 ,	nbfix number: 37932
Using force field file: charmm36.ff/nbfix.itp ,	nb number: 0 ,	nbfix number: 96
Using force field file: charmm36.ff/silcs.itp ,	nb number: 2 ,	nbfix number: 2
Solute BENX	 Movement 266 times	Insert 73 times	Delete 80 times	Translate 54 times	Rotate 59 times	
Solute PRPX	 Movement 262 times	Insert 77 times	Delete 67 times	Translate 67 times	Rotate 51 times	
Solute DMEE	 Movement 264 times	Insert 81 times	Delete 81 times	Translate 48 times	Rotate 54 times	
Solute MEOH	 Movement 243 times	Insert 74 times	Delete 65 times	Translate 59 times	Rotate 45 times	
Solute FORM	 Movement 232 times	Insert 67 times	Delete 70 times	Transl

In [116]:
gcmc.ff,gcmc.ff_pairs

(array([0.35500532, 0.29288   , 0.29850453, ..., 0.28377268, 0.18481694,
        0.40131518], dtype=float32),
 [[0.355005321205, 0.29288],
  [0.2985045245005, 0.19173496707695234],
  [0.1775026606025, 0.0],
  [0.2968830888335, 0.17149638363534084],
  [0.346773417049, 0.110698234855],
  [0.346773417049, 0.110698234855],
  [0.2968830888335, 0.207097434073916],
  [0.3245009490955, 0.3500585551018572],
  [0.3347462843545, 0.48518274907502634],
  [0.197503336825, 0.2374187962230455],
  [0.25768354523500003, 0.2374187962230455],
  [0.3556824042305, 0.36714450996848635],
  [0.3423189234585, 0.4950575562497758],
  [0.302228481142, 0.383469934154],
  [0.36459139141200003, 0.2475287781248879],
  [0.3423189234585, 0.4950575562497758],
  [0.3735003785935, 0.1565509450626217],
  [0.3423189234585, 0.4950575562497758],
  [0.3556824042305, 0.29288],
  [0.3289554426865, 0.3834699341539047],
  [0.1775026606025, 0.0],
  [0.346773417049, 0.110698234855],
  [0.3423189234585, 0.4950575562497758],
  [0.19750

In [109]:
gcmc.atomtypes1,  gcmc.atomtypes2

(['CG2R61',
  'HGR61',
  'LP',
  'HGA3',
  'CG331',
  'CG321',
  'HGA2',
  'OG301',
  'OG311',
  'HGP1',
  'HGR52',
  'CG2O1',
  'NG2S2',
  'OG2D1',
  'CG2R51',
  'NG2R51',
  'CG2R53',
  'NG2R50',
  'CG2O3',
  'OG2D2',
  'LQ',
  'CG334',
  'NG3P3',
  'HGP2',
  'OT',
  'HT'],
 ['CG2R61',
  'HGR61',
  'LP',
  'HGA3',
  'CG331',
  'CG321',
  'HGA2',
  'OG301',
  'OG311',
  'HGP1',
  'HGR52',
  'CG2O1',
  'NG2S2',
  'OG2D1',
  'CG2R51',
  'NG2R51',
  'CG2R53',
  'NG2R50',
  'CG2O3',
  'OG2D2',
  'LQ',
  'CG334',
  'NG3P3',
  'HGP2',
  'OT',
  'HT',
  'NH3',
  'HC',
  'CT1',
  'HB1',
  'CT2A',
  'HA2',
  'CC',
  'OC',
  'C',
  'O',
  'NH1',
  'H',
  'CT2',
  'HA1',
  'CT3',
  'HA3',
  'N',
  'CP3',
  'CP1',
  'CP2',
  'OH1',
  'NH2',
  'CA',
  'HP',
  'CY',
  'NY',
  'CPT',
  'CAI',
  'NR1',
  'CPH1',
  'CPH2',
  'HR1',
  'NR2',
  'HR3',
  'HB2',
  'S',
  'HS',
  'NC2'])

In [94]:
gcmc.fragmentInfo,gcmc.moveArray,gcmc.SimInfo

(array([(b'BENX', 2012,  11.61,  0.25, 400, 0.025,   287,    715, 13, [([-6.9946152e-01, -1.2120769e+00,  0.0000000e+00], -1.1500000e-01,         0), ([-1.2404616e+00, -2.1480770e+00,  0.0000000e+00],  1.1500000e-01,         1), ([ 7.0153844e-01, -1.2120769e+00,  0.0000000e+00], -1.1500000e-01,         0), ([ 1.2425385e+00, -2.1480770e+00,  0.0000000e+00],  1.1500000e-01,         1), ([-1.4004616e+00,  1.9230769e-03,  0.0000000e+00], -1.1500000e-01,         0), ([-2.4814615e+00,  1.9230769e-03,  0.0000000e+00],  1.1500000e-01,         1), ([ 1.4025384e+00,  1.9230769e-03,  0.0000000e+00], -1.1500000e-01,         0), ([ 2.4835384e+00,  1.9230769e-03,  0.0000000e+00],  1.1500000e-01,         1), ([-6.9946152e-01,  1.2159231e+00,  0.0000000e+00], -1.1500000e-01,         0), ([-1.2404616e+00,  2.1509230e+00,  0.0000000e+00],  1.1500000e-01,         1), ([ 7.0153844e-01,  1.2159231e+00,  0.0000000e+00], -1.1500000e-01,         0), ([ 1.2425385e+00,  2.1509230e+00,  0.0000000e+00],  1.150000

In [25]:
from gcmcpy.gcmc_energy import rotate_atoms_shared

In [26]:
gcmc.SimInfo[0],gcmc.SimInfo['totalGridNum']

((10000, 15., 1., [-0.4875, -0.253 ,  0.116 ], [132.126, 132.213, 122.07 ], 0, 0.9006044, 9, 1914440, 150977, 511971, 26, 64, 0, 4232790286),
 array([1914440], dtype=int32))

In [27]:
moveFragType=gcmc.moveArray[0]//4
moveMoveType=gcmc.moveArray[0]%4
# print(moveFragType,moveMoveType)
maxNum=gcmc.fragmentInfo[moveFragType]['maxNum']
totalNum=gcmc.fragmentInfo[moveFragType]['totalNum']
numBlocks = gcmc.fragmentInfo[moveFragType]['confBias']
print(maxNum,totalNum,numBlocks)

723 256 200


In [28]:
#TODO TEST  randomFragment IN energy.py
# gcmc.fragmentInfo['atoms']
# gcmc.fragmentInfo['num_atoms']
SharedInfo = gcmc.SimInfo[0]  # Copy global information to shared memory
SharedFragmentInfo = gcmc.fragmentInfo[moveFragType]  # Copy fragment information
atoms= gcmc.fragmentInfo[moveFragType]['atoms']
num_atoms= gcmc.fragmentInfo[moveFragType]['num_atoms']

randomR = np.random.uniform(0, 1, 3) * gcmc.SimInfo['grid_dx']
axis = np.random.uniform(0, 1, 3)  # Generates a random 3D vector for the rotation axis
angle = np.random.uniform(0, 1) * 2 * np.pi  # Generates a random rotation angle in radians (between 0 and 2π)
gridN = np.random.randint(0, gcmc.SimInfo['totalGridNum'][0])#totalGridNum xyz/one point
randomR += gcmc.grid[gridN * 3: gridN * 3 + 3]#gcmc.grid [x1,y1,z1,x2.....]
# print([randomR,randomThi,randomPhi,gridN])

In [29]:
atoms

array([([-7.6562500e-01,  5.3750002e-03,  0.0000000e+00], -3.7000000e-01,         4),
       ([ 7.4137503e-01, -6.2499999e-04, -0.0000000e+00],  6.2000000e-01,        18),
       ([-1.1356250e+00,  1.0503750e+00,  0.0000000e+00],  9.0000004e-02,         3),
       ([-1.1246250e+00, -5.2062500e-01,  9.0600002e-01],  9.0000004e-02,         3),
       ([-1.1246250e+00, -5.2062500e-01, -9.0600002e-01],  9.0000004e-02,         3),
       ([ 1.2953750e+00,  1.1263750e+00,  0.0000000e+00], -7.5999999e-01,        19),
       ([ 1.2723750e+00, -1.1386250e+00, -0.0000000e+00], -7.5999999e-01,        19),
       ([ 8.4137499e-01, -1.6250000e-03, -0.0000000e+00],  0.0000000e+00,        20),
       ([ 4.5692139e-41,  8.6434038e-24,  4.5692139e-41],  8.6434795e-24,     32607),
       ([ 8.6435552e-24,  4.5692139e-41,  8.6436310e-24],  4.5692139e-41, 421998992),
       ([ 4.5692139e-41,  8.6437824e-24,  4.5692139e-41],  8.6438582e-24,     32607),
       ([ 8.6439339e-24,  4.5692139e-41,  8.6440096e-2

In [104]:
gcmc.simInfo.type.names

AttributeError: 'GCMC' object has no attribute 'simInfo'

In [30]:
#rotate then tranlateing 
axis = axis / np.linalg.norm(axis)
# Compute the rotation matrix
c = np.cos(angle)
s = np.sin(angle)
C = 1 - c
R = np.zeros((3, 3))
R[0][0] = axis[0] * axis[0] * C + c
R[0][1] = axis[0] * axis[1] * C - axis[2] * s
R[0][2] = axis[0] * axis[2] * C + axis[1] * s
R[1][0] = axis[1] * axis[0] * C + axis[2] * s
R[1][1] = axis[1] * axis[1] * C + c
R[1][2] = axis[1] * axis[2] * C - axis[0] * s
R[2][0] = axis[2] * axis[0] * C - axis[1] * s
R[2][1] = axis[2] * axis[1] * C + axis[0] * s
R[2][2] = axis[2] * axis[2] * C + c
# Apply the rotation matrix
# Rotate the atoms
for i in range(num_atoms):
    atom_position = np.copy(atoms[i]['position'])
    atoms[i]['position'] = np.dot(R, atom_position)


In [31]:
from gcmcpy.gcmc_energy import distanceP

In [32]:
#translate all frag atoms 
for i in range(num_atoms):
    atoms[i]['position'] += randomR

In [100]:
SharedFragmentInfo['atoms']['type'][4] , SharedInfo['ffYNum'], gcmc.atomInfo[2]['type']

(3, 64, 27)

In [101]:
gcmc.gff

AttributeError: 'GCMC' object has no attribute 'gff'

In [99]:
typeij = SharedFragmentInfo['atoms']['type'][4] * SharedInfo['ffYNum'] + gcmc.atomInfo[2]['type']
typeij


219

In [41]:
gcmc.SimInfo['ffYNum'], gcmc.SimInfo['cutoff'][0], gcmc.residueInfo[4892],gcmc.residueInfo[4892].dtype.names

(array([64], dtype=int32),
 15.0,
 ([0., 0., 0.], 6, 59280),
 ('position', 'atomNum', 'atomStart'))

In [ ]:
# calcProtEnergy(SharedInfo, SharedFragmentInfo, GfragmentInfo, GresidueInfo, GatomInfo, Gff, GTempInfo, sh_energy)
maxResidueNum =gcmc.fragmentInfo['startRes']
for resi in range(maxResidueNum):
    if distanceP(GTempInfo['position'], GresidueInfo[resi]['position'], SharedInfo['cryst']) > SharedInfo['cutoff']:
        continue

maxResidueNum
# calcFragEnergy(SharedInfo, SharedFragmentInfo, GfragmentInfo, GresidueInfo, GatomInfo, Gff, GTempInfo, sh_energy)


array([2012, 2755, 3467, 4175, 4892, 5611, 6316, 7027, 7741], dtype=int32)

In [ ]:
#TODO cpu first run, rename varible system
# Calculate energy
# calcEnergy(SharedInfo, SharedFragmentInfo, GfragmentInfo, GresidueInfo, GatomInfo, Gff, GTempInfo[cp.blockIdx.x])
maxResidueNum =gcmc.fragmentInfo['startRes'],len(gcmc.fragmentInfo['startRes'])


(array([2012, 2755, 3467, 4175, 4892, 5611, 6316, 7027, 7741], dtype=int32), 9)

In [ ]:
list(randomThi.data),randomThi,randomPhi

([0.06866707700533226, 0.17266550069593023, 0.057529314044472146],
 array([0.06866708, 0.1726655 , 0.05752931]),
 3.155087808419169)

In [ ]:
cp.linalg.norm

In [ ]:
# rotate_atoms_shared(atoms, num_atoms, axis, angle):
# rotate_atoms_shared(SharedFragmentInfo['atoms'], SharedFragmentInfo['num_atoms'], axis, angle)
axis/np.linalg.norm(axis)

array([0.86063476, 0.27572848, 0.42811401])

In [ ]:
SharedFragmentInfo['atoms'], SharedFragmentInfo['num_atoms']

(array([([-6.99461520e-01, -1.21207690e+00,  0.00000000e+00], -1.1500000e-01,           0),
        ([-1.24046159e+00, -2.14807701e+00,  0.00000000e+00],  1.1500000e-01,           1),
        ([ 7.01538444e-01, -1.21207690e+00,  0.00000000e+00], -1.1500000e-01,           0),
        ([ 1.24253845e+00, -2.14807701e+00,  0.00000000e+00],  1.1500000e-01,           1),
        ([-1.40046155e+00,  1.92307692e-03,  0.00000000e+00], -1.1500000e-01,           0),
        ([-2.48146152e+00,  1.92307692e-03,  0.00000000e+00],  1.1500000e-01,           1),
        ([ 1.40253842e+00,  1.92307692e-03,  0.00000000e+00], -1.1500000e-01,           0),
        ([ 2.48353839e+00,  1.92307692e-03,  0.00000000e+00],  1.1500000e-01,           1),
        ([-6.99461520e-01,  1.21592307e+00,  0.00000000e+00], -1.1500000e-01,           0),
        ([-1.24046159e+00,  2.15092301e+00,  0.00000000e+00],  1.1500000e-01,           1),
        ([ 7.01538444e-01,  1.21592307e+00,  0.00000000e+00], -1.1500000e-01,   

In [ ]:
gcmc.grid,len(gcmc.grid)/1914440

(array([ 39.5125,  24.747 ,  89.116 , ..., 103.5125, 130.747 ,  72.116 ],
       dtype=float32),
 3.0)

In [ ]:
xx=[0 for i in range(len(gcmc.attempt_prob_frag) * len(gcmc.fragmentName))]
len(xx)

36

In [ ]:
len(gcmc.moveArray_n),min(gcmc.moveArray),max(gcmc.moveArray),gcmc.moveArray.shape

(36, 0, 35, (10000,))

In [ ]:
gcmc.mctime,len(gcmc.fragmentName),sum([0.025, 0.025, 0.025, 0.025, 0.025, 0.025, 0.025, 0.025, 0.8])

([0.025, 0.025, 0.025, 0.025, 0.025, 0.025, 0.025, 0.025, 0.8], 9, 1.0)

In [ ]:
random.choices(range(len(gcmc.attempt_prob_water)), weights=gcmc.attempt_prob_water, k=1)

[1]

In [ ]:
gcmc.startTime = time.time()
print('Start GPU simulation...')


Start GPU simulation...


In [ ]:
gcmc.SimInfo

array([(10000, 15., 1., [-0.4875, -0.253 ,  0.116 ], [132.126, 132.213, 122.07 ], 0, 0.9006044, 9, 1914440, 151002, 511887, 26, 64, 0, 373883002)],
      dtype=[('mcsteps', '<i4'), ('cutoff', '<f4'), ('grid_dx', '<f4'), ('startxyz', '<f4', (3,)), ('cryst', '<f4', (3,)), ('showInfo', '<i4'), ('cavityFactor', '<f4'), ('fragTypeNum', '<i4'), ('totalGridNum', '<i4'), ('totalResNum', '<i4'), ('totalAtomNum', '<i4'), ('ffXNum', '<i4'), ('ffYNum', '<i4'), ('PME', '<i4'), ('seed', '<u4')])

In [ ]:
[gcmc.SimInfo,
# gcmc.fragmentInfo,
# gcmc.residueInfo,
# gcmc.atomInfo,
# gcmc.grid,
# gcmc.ff,
# gcmc.moveArray
]
#ValueError: Unsupported dtype [('mcsteps', '<i4'), ('cutoff', '<f4'), ('grid_dx', '<f4'), ('startxyz', '<f4', (3,)), ('cryst', '<f4', (3,)), ('showInfo', '<i4'), ('cavityFactor', '<f4'), ('fragTypeNum', '<i4'), ('totalGridNum', '<i4'), ('totalResNum', '<i4'), ('totalAtomNum', '<i4'), ('ffXNum', '<i4'), ('ffYNum', '<i4'), ('PME', '<i4'), ('seed', '<u4')]


[array([(10000, 15., 1., [-0.4875, -0.253 ,  0.116 ], [132.126, 132.213, 122.07 ], 0, 0.9006044, 9, 1914440, 151002, 511887, 26, 64, 0, 373883002)],
       dtype=[('mcsteps', '<i4'), ('cutoff', '<f4'), ('grid_dx', '<f4'), ('startxyz', '<f4', (3,)), ('cryst', '<f4', (3,)), ('showInfo', '<i4'), ('cavityFactor', '<f4'), ('fragTypeNum', '<i4'), ('totalGridNum', '<i4'), ('totalResNum', '<i4'), ('totalAtomNum', '<i4'), ('ffXNum', '<i4'), ('ffYNum', '<i4'), ('PME', '<i4'), ('seed', '<u4')])]

In [ ]:
for frag in gcmc.fragmentInfo:
    print(frag)

(b'BENX', 2012, 11.61, 0.25, 400, 0.025, 287, 710, 13, [([-6.9946152e-01, -1.2120769e+00,  0.0000000e+00], -1.1500000e-01,         0), ([-1.2404616e+00, -2.1480770e+00,  0.0000000e+00],  1.1500000e-01,         1), ([ 7.0153844e-01, -1.2120769e+00,  0.0000000e+00], -1.1500000e-01,         0), ([ 1.2425385e+00, -2.1480770e+00,  0.0000000e+00],  1.1500000e-01,         1), ([-1.4004616e+00,  1.9230769e-03,  0.0000000e+00], -1.1500000e-01,         0), ([-2.4814615e+00,  1.9230769e-03,  0.0000000e+00],  1.1500000e-01,         1), ([ 1.4025384e+00,  1.9230769e-03,  0.0000000e+00], -1.1500000e-01,         0), ([ 2.4835384e+00,  1.9230769e-03,  0.0000000e+00],  1.1500000e-01,         1), ([-6.9946152e-01,  1.2159231e+00,  0.0000000e+00], -1.1500000e-01,         0), ([-1.2404616e+00,  2.1509230e+00,  0.0000000e+00],  1.1500000e-01,         1), ([ 7.0153844e-01,  1.2159231e+00,  0.0000000e+00], -1.1500000e-01,         0), ([ 1.2425385e+00,  2.1509230e+00,  0.0000000e+00],  1.1500000e-01,         

In [ ]:
frag['confBias']

2

In [ ]:
# gcmc.fragmentInfo
maxConf=max(frag['confBias'] for frag in gcmc.fragmentInfo)

In [ ]:
d_rng_states = cp.zeros((maxConf, 8), dtype=cp.uint32)
d_rng_states

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint32)

In [ ]:
gcmc.moveArray_n

[68,
 81,
 46,
 44,
 96,
 73,
 36,
 48,
 71,
 63,
 55,
 46,
 80,
 72,
 56,
 52,
 68,
 63,
 63,
 40,
 63,
 78,
 56,
 65,
 69,
 84,
 57,
 54,
 74,
 92,
 47,
 52,
 1987,
 2069,
 2021,
 1911]

In [ ]:
griddx=1.0
wdens=55.0
fdens=0.25
HFE = {
    'standard': [
        { 'name':'benx', 'hfe':-0.79,  'muex':-0.79,  'muexdx':1.0 },
        { 'name':'prpx', 'hfe':1.96,   'muex':1.96,   'muexdx':1.0 },
        { 'name':'aald', 'hfe':-3.23,  'muex':-3.23,  'muexdx':1.0 },
        { 'name':'meoh', 'hfe':-5.36,  'muex':-5.36,  'muexdx':1.0 },
        { 'name':'form', 'hfe':-10.92, 'muex':-10.92, 'muexdx':2.0 },
        { 'name':'imia', 'hfe':-14.18, 'muex':-14.18, 'muexdx':2.0 },
        { 'name':'acey', 'hfe':-97.31, 'muex':-97.31, 'muexdx':10.0 },
        { 'name':'mamy', 'hfe':-68.49, 'muex':-68.49, 'muexdx':10.0 },
        { 'name':'sol',  'hfe':-5.6,   'muex':-5.6,   'muexdx':2.0 },
    ],
    'halogen': [
        { 'name':'dmee', 'hfe':-1.44, 'muex':-1.79, 'muexdx':1.0 },
        { 'name':'clbx', 'hfe':-1.18, 'muex':-1.19, 'muexdx':1.0 },
        { 'name':'tfex', 'hfe':-0.15, 'muex':-0.05, 'muexdx':1.0 },
        { 'name':'meoh', 'hfe':-5.36, 'muex':-5.36, 'muexdx':1.0 },
        { 'name':'flbx', 'hfe':-0.80, 'muex':-0.13, 'muexdx':1.0 },
        { 'name':'clex', 'hfe':-0.63, 'muex':-0.15, 'muexdx':1.0 },
        { 'name':'brbx', 'hfe':-1.48, 'muex':-0.36, 'muexdx':1.0 },
        { 'name':'fetx', 'hfe':-0.10, 'muex':-0.96, 'muexdx':1.0 },
        { 'name':'sol',  'hfe':-5.60, 'muex':-5.6,  'muexdx':1.0 },
    ]
}
FragData=[]
probe='standard'
for fragment in HFE[probe]:
    fragment['iter'] = 0
    fragment['lhfe'] = 0
    fragment['uhfe'] = 0
    fragment['mctime'] = 1.0 / len(HFE[probe])
    if fragment['name'] == 'sol':
        fragment['conc'] = wdens
    else:
        fragment['conc'] = fdens
    FragData.append(fragment)

In [ ]:
FragData

[{'name': 'benx',
  'hfe': -0.79,
  'muex': -0.79,
  'muexdx': 1.0,
  'iter': 0,
  'lhfe': 0,
  'uhfe': 0,
  'mctime': 0.1111111111111111,
  'conc': 0.25},
 {'name': 'prpx',
  'hfe': 1.96,
  'muex': 1.96,
  'muexdx': 1.0,
  'iter': 0,
  'lhfe': 0,
  'uhfe': 0,
  'mctime': 0.1111111111111111,
  'conc': 0.25},
 {'name': 'aald',
  'hfe': -3.23,
  'muex': -3.23,
  'muexdx': 1.0,
  'iter': 0,
  'lhfe': 0,
  'uhfe': 0,
  'mctime': 0.1111111111111111,
  'conc': 0.25},
 {'name': 'meoh',
  'hfe': -5.36,
  'muex': -5.36,
  'muexdx': 1.0,
  'iter': 0,
  'lhfe': 0,
  'uhfe': 0,
  'mctime': 0.1111111111111111,
  'conc': 0.25},
 {'name': 'form',
  'hfe': -10.92,
  'muex': -10.92,
  'muexdx': 2.0,
  'iter': 0,
  'lhfe': 0,
  'uhfe': 0,
  'mctime': 0.1111111111111111,
  'conc': 0.25},
 {'name': 'imia',
  'hfe': -14.18,
  'muex': -14.18,
  'muexdx': 2.0,
  'iter': 0,
  'lhfe': 0,
  'uhfe': 0,
  'mctime': 0.1111111111111111,
  'conc': 0.25},
 {'name': 'acey',
  'hfe': -97.31,
  'muex': -97.31,
  'muexdx

In [ ]:
gcmc.fragmentInfo

array([(b'BENX', 2012,  11.61,  0.25, 400, 0.025,   287,    710, 13, [([-6.9946152e-01, -1.2120769e+00,  0.0000000e+00], -1.1500000e-01,         0), ([-1.2404616e+00, -2.1480770e+00,  0.0000000e+00],  1.1500000e-01,         1), ([ 7.0153844e-01, -1.2120769e+00,  0.0000000e+00], -1.1500000e-01,         0), ([ 1.2425385e+00, -2.1480770e+00,  0.0000000e+00],  1.1500000e-01,         1), ([-1.4004616e+00,  1.9230769e-03,  0.0000000e+00], -1.1500000e-01,         0), ([-2.4814615e+00,  1.9230769e-03,  0.0000000e+00],  1.1500000e-01,         1), ([ 1.4025384e+00,  1.9230769e-03,  0.0000000e+00], -1.1500000e-01,         0), ([ 2.4835384e+00,  1.9230769e-03,  0.0000000e+00],  1.1500000e-01,         1), ([-6.9946152e-01,  1.2159231e+00,  0.0000000e+00], -1.1500000e-01,         0), ([-1.2404616e+00,  2.1509230e+00,  0.0000000e+00],  1.1500000e-01,         1), ([ 7.0153844e-01,  1.2159231e+00,  0.0000000e+00], -1.1500000e-01,         0), ([ 1.2425385e+00,  2.1509230e+00,  0.0000000e+00],  1.1500000

In [ ]:
from collections import defaultlist

ImportError: cannot import name 'defaultlist' from 'collections' (/home/jovyan/bo2/miniconda/envs/g9/lib/python3.10/collections/__init__.py)

In [ ]:
for i, frag in enumerate(FragData):


In [ ]:
for i, frag in enumerate(FragData):



    self.fragmentInfo[i]['name'] = self.fragmentName[i]
    # fragmentInfo[i]['name'] = np.array(self.fragmentName[i].ljust(4)[:4], dtype='S4')

    
    self.fragmentInfo[i]['muex'] = self.fragmuex[i]
    self.fragmentInfo[i]['conc'] = self.fragconc[i]
    self.fragmentInfo[i]['confBias'] = self.fragconf[i]
    self.fragmentInfo[i]['mcTime'] = self.mctime[i]

    self.fragmentInfo[i]['totalNum'] = len(self.fraglist[i])

    # Two times of the number of fragments or the number of fragments plus the number of fragments in the largest configuration
    
    maxNum1 = self.fragconc[i] * self.volume * MOLES_TO_MOLECULES * 2 + self.moveArray_n[i*4]
    maxNum2 = len(self.fraglist[i]) + self.moveArray_n[i*4] 

    self.fragmentInfo[i]['maxNum'] = max(maxNum1, maxNum2)

    print(f"Solute {self.fragmentName[i]}: Total number: {self.fragmentInfo[i]['totalNum']}, Max number: {self.fragmentInfo[i]['maxNum']}")

    self.fragmentInfo[i]['num_atoms'] = len(frag)



In [ ]:
maxConf = max(frag.confBias for frag in gcmc.fragmentInfo)

AttributeError: 'numpy.void' object has no attribute 'confBias'

In [ ]:
import cupy as  cp

In [ ]:
cp.array(gcmc.fragmentInfo)

ValueError: Unsupported dtype [('mcsteps', '<i4'), ('cutoff', '<f4'), ('grid_dx', '<f4'), ('startxyz', '<f4', (3,)), ('cryst', '<f4', (3,)), ('showInfo', '<i4'), ('cavityFactor', '<f4'), ('fragTypeNum', '<i4'), ('totalGridNum', '<i4'), ('totalResNum', '<i4'), ('totalAtomNum', '<i4'), ('ffXNum', '<i4'), ('ffYNum', '<i4'), ('PME', '<i4'), ('seed', '<u4')]

In [ ]:
gcmc.run()

Start GPU simulation...


ValueError: Unsupported dtype [('mcsteps', '<i4'), ('cutoff', '<f4'), ('grid_dx', '<f4'), ('startxyz', '<f4', (3,)), ('cryst', '<f4', (3,)), ('showInfo', '<i4'), ('cavityFactor', '<f4'), ('fragTypeNum', '<i4'), ('totalGridNum', '<i4'), ('totalResNum', '<i4'), ('totalAtomNum', '<i4'), ('ffXNum', '<i4'), ('ffYNum', '<i4'), ('PME', '<i4'), ('seed', '<u4')]

In [ ]:
[gcmc.SimInfo,
gcmc.fragmentInfo,
gcmc.residueInfo,
gcmc.atomInfo,
gcmc.grid,
gcmc.ff,
gcmc.moveArray]

AttributeError: 'GCMC' object has no attribute 'SimInfo'