In [1]:
import openmm as mm
from openmm.app import *
from openmm import *
from openmm.unit import *

In [2]:
pdb = PDBFile('6v3g_silcs.1.pdb')
PeriodicBoxVectors = pdb.topology.getPeriodicBoxVectors()
topo = GromacsTopFile('6v3g_silcs.1.top' , periodicBoxVectors=PeriodicBoxVectors,
                                  includeDir='./')
system = topo.createSystem(nonbondedMethod=CutoffPeriodic, nonbondedCutoff= 2 ,
                                                  constraints=HBonds)
integrator = LangevinMiddleIntegrator(298 * kelvin , 1 / picoseconds, 0.002 * picoseconds)
simulation = Simulation(topo.topology, system, integrator)
simulation.context.setPositions(pdb.positions)
state = simulation.context.getState(getEnergy=True)
print('Initial energy: ', state.getPotentialEnergy())

Initial energy:  67720432.24309993 kJ/mol


In [14]:
pdb = PDBFile('6v3g_silcs.2.pdb')
PeriodicBoxVectors = pdb.topology.getPeriodicBoxVectors()
topo = GromacsTopFile('6v3g_silcs.2.top' , periodicBoxVectors=PeriodicBoxVectors,
                                  includeDir='./')
system = topo.createSystem(nonbondedMethod=CutoffPeriodic, nonbondedCutoff= 1.5 ,
                                                  constraints=HBonds)
integrator = LangevinMiddleIntegrator(298 * kelvin , 1 / picoseconds, 0.002 * picoseconds)
simulation = Simulation(topo.topology, system, integrator)
simulation.context.setPositions(pdb.positions)
state = simulation.context.getState(getEnergy=True)
print('Initial energy: ', state.getPotentialEnergy())

Initial energy:  67770795.67961206 kJ/mol


In [3]:
pdb = PDBFile('6v3g_silcs.3.pdb')
PeriodicBoxVectors = pdb.topology.getPeriodicBoxVectors()
topo = GromacsTopFile('6v3g_silcs.3.top' , periodicBoxVectors=PeriodicBoxVectors,
                                  includeDir='./')
system = topo.createSystem(nonbondedMethod=CutoffPeriodic, nonbondedCutoff= 2 ,
                                                  constraints=HBonds)
integrator = LangevinMiddleIntegrator(298 * kelvin , 1 / picoseconds, 0.002 * picoseconds)
simulation = Simulation(topo.topology, system, integrator)
simulation.context.setPositions(pdb.positions)
state = simulation.context.getState(getEnergy=True)
print('Initial energy: ', state.getPotentialEnergy())

Initial energy:  67720064.1905509 kJ/mol


In [16]:
67770795.67961206 - 67758683.8041696

12111.87544246018

In [3]:
67758547.67961206 - 67758683.8041696

-136.12455753982067

In [5]:
67720064.1905509 - 67720432.24309993

-368.05254903435707

In [2]:
pdb = PDBFile('2water.pdb')
PeriodicBoxVectors = pdb.topology.getPeriodicBoxVectors()
topo = GromacsTopFile('2water.top' , periodicBoxVectors=PeriodicBoxVectors,
                                  includeDir='./')
system = topo.createSystem(nonbondedMethod=CutoffPeriodic, nonbondedCutoff= 1.5 ,
                                                  constraints=HBonds)
integrator = LangevinMiddleIntegrator(298 * kelvin , 1 / picoseconds, 0.002 * picoseconds)
simulation = Simulation(topo.topology, system, integrator)
simulation.context.setPositions(pdb.positions)
state = simulation.context.getState(getEnergy=True)
print('Initial energy: ', state.getPotentialEnergy())

Initial energy:  9.306696917118645 kJ/mol


In [3]:
pdb = PDBFile('3water.pdb')
PeriodicBoxVectors = pdb.topology.getPeriodicBoxVectors()
topo = GromacsTopFile('3water.top' , periodicBoxVectors=PeriodicBoxVectors,
                                  includeDir='./')
system = topo.createSystem(nonbondedMethod=CutoffPeriodic, nonbondedCutoff= 1.5 ,
                                                  constraints=HBonds)
integrator = LangevinMiddleIntegrator(298 * kelvin , 1 / picoseconds, 0.002 * picoseconds)
simulation = Simulation(topo.topology, system, integrator)
simulation.context.setPositions(pdb.positions)
state = simulation.context.getState(getEnergy=True)
print('Initial energy: ', state.getPotentialEnergy())

Initial energy:  193.23521227295663 kJ/mol


In [4]:
193.23521227295663 - 9.306696917118645

183.928515355838

In [ ]:
183.497314

In [5]:
from simtk.openmm.app import *
from simtk.openmm import *
from simtk.unit import *

pdb = PDBFile('3water.pdb')
PeriodicBoxVectors = pdb.topology.getPeriodicBoxVectors()
topo = GromacsTopFile('3water.top' , periodicBoxVectors=PeriodicBoxVectors,
                                  includeDir='./')
system = topo.createSystem(nonbondedMethod=CutoffPeriodic, nonbondedCutoff=1.5,
                                                  constraints=HBonds)

# Find the NonbondedForce object in the system, and zero out charges.
for force in system.getForces():
    if isinstance(force, NonbondedForce):
        for i in range(force.getNumParticles()):
            charge, sigma, epsilon = force.getParticleParameters(i)
            force.setParticleParameters(i, Quantity(value=0.0, unit=elementary_charge), sigma, epsilon)

integrator = LangevinMiddleIntegrator(298 * kelvin , 1 / picoseconds, 0.002 * picoseconds)
simulation = Simulation(topo.topology, system, integrator)
simulation.context.setPositions(pdb.positions)
state = simulation.context.getState(getEnergy=True)
print('Initial energy: ', state.getPotentialEnergy())


Initial energy:  196.796583122566 kJ/mol


In [6]:
from simtk.openmm.app import *
from simtk.openmm import *
from simtk.unit import *

pdb = PDBFile('2water.pdb')
PeriodicBoxVectors = pdb.topology.getPeriodicBoxVectors()
topo = GromacsTopFile('2water.top' , periodicBoxVectors=PeriodicBoxVectors,
                                  includeDir='./')
system = topo.createSystem(nonbondedMethod=CutoffPeriodic, nonbondedCutoff=1.5,
                                                  constraints=HBonds)

# Find the NonbondedForce object in the system, and zero out charges.
for force in system.getForces():
    if isinstance(force, NonbondedForce):
        for i in range(force.getNumParticles()):
            charge, sigma, epsilon = force.getParticleParameters(i)
            force.setParticleParameters(i, Quantity(value=0.0, unit=elementary_charge), sigma, epsilon)

integrator = LangevinMiddleIntegrator(298 * kelvin , 1 / picoseconds, 0.002 * picoseconds)
simulation = Simulation(topo.topology, system, integrator)
simulation.context.setPositions(pdb.positions)
state = simulation.context.getState(getEnergy=True)
print('Initial energy: ', state.getPotentialEnergy())

Initial energy:  16.735997225346182 kJ/mol


In [7]:
196.796583122566 - 16.735997225346182

180.06058589721982

In [8]:
sigmaO = 0.315057422683  
epsilonO = 0.63639
sigmaH = 0.0400013524445 
episilonH = 0.192464


In [11]:
s = '''ATOM  23610  OW  SOL A 449      30.871  40.491 153.455  1.00  0.00
ATOM  23611  HW1 SOL A 449      31.521  39.751 153.345  1.00  0.00
ATOM  23612  HW2 SOL A 449      31.071  40.991 154.295  1.00  0.00
ATOM  38550  OW  SOL A9779      29.868  41.693 155.535  1.00  0.00
ATOM  38551  HW1 SOL A9779      30.450  42.453 155.502  1.00  0.00
ATOM  38552  HW2 SOL A9779      29.231  41.908 156.216  1.00  0.00
'''
s2 ='''ATOM  38553  OW  SOL A9780      32.191  40.158 155.174  1.00  0.00
ATOM  38554  HW1 SOL A9780      32.897  40.773 155.372  1.00  0.00
ATOM  38555  HW2 SOL A9780      32.576  39.543 154.550  1.00  0.00'''

In [10]:
# sigma_sqrd = sigma * sigma * 100
# sigma_dist_sqrd = sigma_sqrd / dist_sqrd
# E_vdw = 4*epsilon * ( pow(sigma_dist_sqrd, 6) - pow(sigma_dist_sqrd, 3) )

In [19]:
import numpy as np

# Define the vector to be rotated, rotation axis and the angle
v = np.array([0.000, 0.000, -0.391])
k = np.array([29.850, 42.018, 155.751])
theta = 0.847

# Normalize k
k_norm = k / np.linalg.norm(k)

# Compute rotated vector
v_rot = v*np.cos(theta) + np.cross(k_norm, v)*np.sin(theta) + k_norm*np.dot(k_norm, v)*(1 - np.cos(theta))

print(v_rot)

[-0.09784862  0.02119442 -0.37796487]


In [20]:

# Define the rotation axis and the angle
k = np.array([29.850, 42.018, 155.751])
theta = 0.847

# Normalize k
k_norm = k / np.linalg.norm(k)

# Define the skew-symmetric matrix K
K = np.array([[0, -k_norm[2], k_norm[1]], 
              [k_norm[2], 0, -k_norm[0]], 
              [-k_norm[1], k_norm[0], 0]])

# Define the identity matrix
I = np.eye(3)

# Compute rotation matrix
R = I + np.sin(theta) * K + (1 - np.cos(theta)) * np.dot(K, K)

print(R)

[[ 0.67341581 -0.69561841  0.25025221]
 [ 0.72709826  0.68439014 -0.05420567]
 [-0.13356368  0.21846091  0.96666208]]


Initial energy:  67758747.8041696 kJ/mol
